export const CREATE_FILEMANAGER_PENDING = 'CREATE_FILEMANAGER_PENDING'

export const FILEMANAGER_API_ERROR = 'FILEMANAGER_API_ERROR'
export const IS_FILEMANAGER_PUBLIC = 'IS_FILEMANAGER_PUBLIC'
export const FILEMANAGER_INTEGRATION_MODE = 'FILEMANAGER_INTEGRATION_MODE'
