export const GET_FOLDER = 'GET_FOLDER'
export const GET_ALL_FOLDERS = 'GET_ALL_FOLDERS'
export const FOLDER_API_ERROR = 'FOLDER_API_ERROR'

export const GET_FOLDER_PENDING = 'GET_FOLDER_PENDING'
export const GET_FOLDERS_PENDING = 'GET_FOLDERS_PENDING'
export const CREATE_FOLDER_PENDING = 'CREATE_FOLDER_PENDING'
export const DELETE_FOLDER_PENDING = 'DELETE_FOLDER_PENDING'
export const UPDATE_FOLDER_PENDING = 'UPDATE_FOLDER_PENDING'
